#!/usr/bin/env bash
# Set the server hostnames and IP addresses
WEB01_HOSTNAME="6145-web-01"
WEB01_IP="44.222.202.229"
WEB02_HOSTNAME="6145-web-02"
WEB02_IP="54.87.50.204"

# Check if HAproxy is installed
if ! command -v haproxy &> /dev/null
then
    echo "HAproxy is not installed. Installing now..."
    sudo apt-get -y update
    sudo apt-get -y install haproxy
fi

# Configure HAproxy
echo "Configuring HAproxy..."
echo "
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        mode http
        balance roundrobin
        server $WEB01_HOSTNAME $WEB01_IP:80 check
        server $WEB02_HOSTNAME $WEB02_IP:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAproxy service
echo "Enabling HAproxy service..."
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAproxy service
echo "Restarting HAproxy service..."
sudo service haproxy restart