#!/usr/bin/env bash
# Update package lists and install Nginx
apt-get update -y && apt-get upgrade -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'

# Installing an index html file
sh -c 'echo "Holberton School" > /var/www/html/index.html'

# Restarting the server with the new config
service nginx restart
